import { controls_type } from "../../../generated/prisma/client";

export type IsoControlCatalogItem = {
  code: string;
  name: string;
  type: controls_type;
  description: string;
  guidance: string;
};

export const ISO27001_CONTROLS_CATALOG: readonly IsoControlCatalogItem[] = [
  /* =========================
     A.5 ORGANISATIONAL (37)
     ========================= */
  {
    code: "A.5.1",
    name: "Policies for information security",
    type: controls_type.ORGANIZATION,
    description: "Define and maintain information security policy(ies) aligned with business and risk.",
    guidance: "Create IS policy set, approve by management, publish to staff, review at least annually; keep version history and communication records.",
  },
  {
    code: "A.5.2",
    name: "Information security roles and responsibilities",
    type: controls_type.ORGANIZATION,
    description: "Assign and document security roles, responsibilities, and authorities.",
    guidance: "Define RACI, job descriptions, ownership for assets/controls, ISMS roles (e.g., ISMS manager); keep org chart/RACI evidence.",
  },
  {
    code: "A.5.3",
    name: "Segregation of duties",
    type: controls_type.ORGANIZATION,
    description: "Reduce risk of error/fraud by separating conflicting duties.",
    guidance: "Split duties for admin/dev/ops, approvals, payments; enforce via access roles and workflow approvals; keep SoD matrix and access reviews.",
  },
  {
    code: "A.5.4",
    name: "Management responsibilities",
    type: controls_type.ORGANIZATION,
    description: "Management must support and enforce information security expectations.",
    guidance: "Set tone, allocate resources, ensure staff follow policies; evidence: leadership communications, meeting minutes, KPIs, approvals.",
  },
  {
    code: "A.5.5",
    name: "Contact with authorities",
    type: controls_type.ORGANIZATION,
    description: "Maintain appropriate contacts with relevant authorities.",
    guidance: "List regulators/law enforcement/CSIRT contacts, define when to contact (incidents); keep contact list and incident playbooks.",
  },
  {
    code: "A.5.6",
    name: "Contact with special interest groups",
    type: controls_type.ORGANIZATION,
    description: "Maintain contacts with security groups/communities where helpful.",
    guidance: "Join ISAC, vendor security bulletins, local CERT communities; document subscriptions and how intel is reviewed.",
  },
  {
    code: "A.5.7",
    name: "Threat intelligence",
    type: controls_type.ORGANIZATION,
    description: "Collect and analyze threat intelligence relevant to the organization.",
    guidance: "Define sources (CERT, vendor, ISAC), triage process, map to assets; evidence: intel reviews, tickets, risk updates.",
  },
  {
    code: "A.5.8",
    name: "Information security in project management",
    type: controls_type.ORGANIZATION,
    description: "Integrate security requirements into project governance and delivery.",
    guidance: "Add security checkpoints (requirements, design review, testing), define acceptance criteria; evidence: project templates, sign-offs.",
  },
  {
    code: "A.5.9",
    name: "Inventory of information and other associated assets",
    type: controls_type.ORGANIZATION,
    description: "Maintain inventory of information/assets with owners and classification.",
    guidance: "Create asset register (systems, data, devices), assign owner, location, criticality; evidence: asset register and review logs.",
  },
  {
    code: "A.5.10",
    name: "Acceptable use of information and associated assets",
    type: controls_type.ORGANIZATION,
    description: "Define rules for acceptable use of assets and information.",
    guidance: "Create AUP policy, cover email, cloud, devices, removable media; evidence: policy acknowledgement and training.",
  },
  {
    code: "A.5.11",
    name: "Return of assets",
    type: controls_type.ORGANIZATION,
    description: "Ensure assets are returned when employment/contract ends or changes.",
    guidance: "Offboarding checklist, collect devices/badges/keys, confirm data return; evidence: signed checklists and asset updates.",
  },
  {
    code: "A.5.12",
    name: "Classification of information",
    type: controls_type.ORGANIZATION,
    description: "Classify information based on value, sensitivity, and criticality.",
    guidance: "Define classification scheme and handling rules; evidence: policy, labels, examples, audits of correct classification.",
  },
  {
    code: "A.5.13",
    name: "Labelling of information",
    type: controls_type.ORGANIZATION,
    description: "Label information and assets according to classification.",
    guidance: "Implement labels in docs, email headers, storage tags; evidence: templates, screenshots, sample labelled files.",
  },
  {
    code: "A.5.14",
    name: "Information transfer",
    type: controls_type.ORGANIZATION,
    description: "Protect information during transfer (internal/external).",
    guidance: "Define approved channels, encryption, DLP rules, secure file sharing; evidence: procedures, configs, logs.",
  },
  {
    code: "A.5.15",
    name: "Access control",
    type: controls_type.ORGANIZATION,
    description: "Establish access control policy and principles for access decisions.",
    guidance: "Least privilege, need-to-know, RBAC; evidence: access policy, role matrix, reviews, joiner/mover/leaver process.",
  },
  {
    code: "A.5.16",
    name: "Identity management",
    type: controls_type.ORGANIZATION,
    description: "Manage identity lifecycle for users and system identities.",
    guidance: "Central directory/SSO, joiner-mover-leaver automation, unique IDs; evidence: IAM procedures and audit trails.",
  },
  {
    code: "A.5.17",
    name: "Authentication information",
    type: controls_type.ORGANIZATION,
    description: "Protect authentication information (passwords, keys, tokens).",
    guidance: "Strong password policy, MFA, secrets management, rotation; evidence: policy, vault configs, rotation logs.",
  },
  {
    code: "A.5.18",
    name: "Access rights",
    type: controls_type.ORGANIZATION,
    description: "Provision, review, modify and revoke access rights securely.",
    guidance: "Approval workflow, periodic access reviews, immediate revocation on exit; evidence: tickets, reviews, deprovision logs.",
  },
  {
    code: "A.5.19",
    name: "Information security in supplier relationships",
    type: controls_type.ORGANIZATION,
    description: "Address information security risks in supplier relationships.",
    guidance: "Supplier risk assessment, due diligence, tiering; evidence: supplier register, assessments, approvals.",
  },
  {
    code: "A.5.20",
    name: "Addressing information security within supplier agreements",
    type: controls_type.ORGANIZATION,
    description: "Include security requirements and responsibilities in supplier contracts.",
    guidance: "Contract clauses: confidentiality, breach notification, audit rights, SLAs, data handling; evidence: templates and signed contracts.",
  },
  {
    code: "A.5.21",
    name: "Managing information security in the ICT supply chain",
    type: controls_type.ORGANIZATION,
    description: "Manage security risks across the ICT supply chain and dependencies.",
    guidance: "Map critical vendors/subprocessors, require controls attestations, monitor changes; evidence: supply chain mapping and reviews.",
  },
  {
    code: "A.5.22",
    name: "Monitoring, review and change management of supplier services",
    type: controls_type.ORGANIZATION,
    description: "Monitor supplier performance and handle changes securely.",
    guidance: "Regular reviews, KPI/SLA checks, change notifications, re-assessment; evidence: review minutes, reports, change records.",
  },
  {
    code: "A.5.23",
    name: "Information security for use of cloud services",
    type: controls_type.ORGANIZATION,
    description: "Ensure cloud use is governed with security requirements and shared responsibility.",
    guidance: "Cloud policy, vendor due diligence, configuration baselines, logging, IAM; evidence: cloud standards, configs, risk assessment.",
  },
  {
    code: "A.5.24",
    name: "Information security incident management planning and preparation",
    type: controls_type.ORGANIZATION,
    description: "Prepare incident management capability and plans.",
    guidance: "Define IR policy, roles, playbooks, escalation, tabletop drills; evidence: IR plan, drills, on-call rota.",
  },
  {
    code: "A.5.25",
    name: "Assessment and decision on information security events",
    type: controls_type.ORGANIZATION,
    description: "Assess events and decide if they are incidents requiring response.",
    guidance: "Define event triage criteria, severity classification, tooling; evidence: triage SOP, ticket examples.",
  },
  {
    code: "A.5.26",
    name: "Response to information security incidents",
    type: controls_type.ORGANIZATION,
    description: "Respond to incidents consistently and effectively.",
    guidance: "Contain/eradicate/recover steps, communications plan, evidence preservation; evidence: incident reports and timelines.",
  },
  {
    code: "A.5.27",
    name: "Learning from information security incidents",
    type: controls_type.ORGANIZATION,
    description: "Use incidents to improve controls and prevent recurrence.",
    guidance: "Post-incident reviews, root cause analysis, corrective actions; evidence: PIR docs and tracked actions.",
  },
  {
    code: "A.5.28",
    name: "Collection of evidence",
    type: controls_type.ORGANIZATION,
    description: "Collect and preserve evidence for investigations/legal needs.",
    guidance: "Chain-of-custody procedure, log retention, forensics readiness; evidence: SOP, sample chain-of-custody records.",
  },
  {
    code: "A.5.29",
    name: "Information security during disruption",
    type: controls_type.ORGANIZATION,
    description: "Maintain information security during business/operational disruption.",
    guidance: "Define minimum security controls during crisis, emergency access, comms; evidence: BC/DR procedures including security.",
  },
  {
    code: "A.5.30",
    name: "ICT readiness for business continuity",
    type: controls_type.ORGANIZATION,
    description: "Ensure ICT can support business continuity requirements (RTO/RPO).",
    guidance: "Set RTO/RPO, backups, DR sites, failover testing; evidence: BCIA, DR test reports, backup reports.",
  },
  {
    code: "A.5.31",
    name: "Legal, statutory, regulatory and contractual requirements",
    type: controls_type.ORGANIZATION,
    description: "Identify and comply with legal/regulatory/contractual security requirements.",
    guidance: "Compliance register, obligations mapping, periodic reviews; evidence: register, gap assessments, audit results.",
  },
  {
    code: "A.5.32",
    name: "Intellectual property rights",
    type: controls_type.ORGANIZATION,
    description: "Protect and respect IP rights and licensing obligations.",
    guidance: "Software license management, IP policy, NDAs; evidence: license inventory, IP clauses, policy acknowledgement.",
  },
  {
    code: "A.5.33",
    name: "Protection of records",
    type: controls_type.ORGANIZATION,
    description: "Protect records from loss, destruction, falsification, unauthorized access.",
    guidance: "Retention policy, integrity controls, backups, access restrictions; evidence: retention schedule, storage controls.",
  },
  {
    code: "A.5.34",
    name: "Privacy and protection of PII",
    type: controls_type.ORGANIZATION,
    description: "Protect personal data/PII and comply with privacy requirements.",
    guidance: "PII inventory, lawful basis, DPIA, access controls, breach handling; evidence: DPIA, privacy policy, data maps.",
  },
  {
    code: "A.5.35",
    name: "Independent review of information security",
    type: controls_type.ORGANIZATION,
    description: "Have independent reviews of information security/ISMS effectiveness.",
    guidance: "Internal audits, external reviews, pentests where needed; evidence: audit plans, reports, corrective actions.",
  },
  {
    code: "A.5.36",
    name: "Compliance with policies, rules and standards for information security",
    type: controls_type.ORGANIZATION,
    description: "Ensure compliance with internal policies and applicable standards.",
    guidance: "Monitoring, audits, awareness, exceptions management; evidence: compliance checks, exceptions register.",
  },
  {
    code: "A.5.37",
    name: "Documented operating procedures",
    type: controls_type.ORGANIZATION,
    description: "Maintain operating procedures for security-relevant activities.",
    guidance: "Create SOPs for backups, patching, access, incidents; evidence: controlled documents and change history.",
  },

  /* =========================
     A.6 PEOPLE (8)
     ========================= */
  {
    code: "A.6.1",
    name: "Screening",
    type: controls_type.PEOPLE,
    description: "Perform background checks before granting access to information/assets.",
    guidance: "Define screening by role risk, verify ID/CV/references; keep records securely and comply with laws.",
  },
  {
    code: "A.6.2",
    name: "Terms and conditions of employment",
    type: controls_type.PEOPLE,
    description: "Employment/contract terms must state security responsibilities.",
    guidance: "Include confidentiality, acceptable use, incident reporting, disciplinary clauses; retain signed contracts and policy acknowledgements.",
  },
  {
    code: "A.6.3",
    name: "Information security awareness, education and training",
    type: controls_type.PEOPLE,
    description: "Ensure people understand security responsibilities and threats.",
    guidance: "Onboarding + annual training, phishing simulations; evidence: training records, attendance, materials, metrics.",
  },
  {
    code: "A.6.4",
    name: "Disciplinary process",
    type: controls_type.PEOPLE,
    description: "Define consequences for security policy violations.",
    guidance: "HR disciplinary policy aligned with local law; evidence: policy, process, anonymized case logs if possible.",
  },
  {
    code: "A.6.5",
    name: "Responsibilities after termination or change of employment",
    type: controls_type.PEOPLE,
    description: "Ensure ongoing obligations and access changes are handled.",
    guidance: "Offboarding: revoke access, return assets, remind confidentiality; evidence: checklist, access revocation logs.",
  },
  {
    code: "A.6.6",
    name: "Confidentiality or non-disclosure agreements",
    type: controls_type.PEOPLE,
    description: "Use NDAs/confidentiality agreements with employees/third parties.",
    guidance: "Standard NDA templates, scope + duration; evidence: signed NDAs and contract clauses.",
  },
  {
    code: "A.6.7",
    name: "Remote working",
    type: controls_type.PEOPLE,
    description: "Secure remote work arrangements and controls.",
    guidance: "Remote policy, VPN/MFA, device security, workspace privacy; evidence: policy, configs, endpoint compliance reports.",
  },
  {
    code: "A.6.8",
    name: "Information security event reporting",
    type: controls_type.PEOPLE,
    description: "Enable timely reporting of security events/weaknesses by staff.",
    guidance: "Define reporting channels, hotline/ticket, non-punitive reporting; evidence: SOP, awareness comms, sample reports.",
  },

  /* =========================
     A.7 PHYSICAL (14)
     ========================= */
  {
    code: "A.7.1",
    name: "Physical security perimeters",
    type: controls_type.PHYSICAL,
    description: "Establish security boundaries to protect facilities and critical areas.",
    guidance: "Use locks, barriers, zoning; define secure areas; evidence: floor plans, access lists, photos (if allowed).",
  },
  {
    code: "A.7.2",
    name: "Physical entry controls",
    type: controls_type.PHYSICAL,
    description: "Control physical access to secure areas.",
    guidance: "Badges, biometrics, visitor logs, escort rules; evidence: access logs, visitor records, procedures.",
  },
  {
    code: "A.7.3",
    name: "Securing offices, rooms and facilities",
    type: controls_type.PHYSICAL,
    description: "Secure offices/rooms to prevent unauthorized access or damage.",
    guidance: "Lock doors, secure server rooms, restrict keys; evidence: key management logs, security checks.",
  },
  {
    code: "A.7.4",
    name: "Physical security monitoring",
    type: controls_type.PHYSICAL,
    description: "Monitor facilities for unauthorized access or incidents.",
    guidance: "CCTV, alarms, guard patrols; evidence: monitoring policy, retention, incident records.",
  },
  {
    code: "A.7.5",
    name: "Protecting against physical and environmental threats",
    type: controls_type.PHYSICAL,
    description: "Protect against fire, flood, power loss, temperature, etc.",
    guidance: "Risk assess site, fire suppression, UPS, HVAC; evidence: maintenance records, inspections, risk assessments.",
  },
  {
    code: "A.7.6",
    name: "Working in secure areas",
    type: controls_type.PHYSICAL,
    description: "Define rules for working in secure areas to prevent leaks.",
    guidance: "No photography rules, clean desk, escort, device restrictions; evidence: signage, SOP, access rules.",
  },
  {
    code: "A.7.7",
    name: "Clear desk and clear screen",
    type: controls_type.PHYSICAL,
    description: "Prevent unauthorized viewing of sensitive info by keeping desks/screens clear.",
    guidance: "Auto screen lock, secure storage, clean desk policy; evidence: policy, endpoint settings, spot-check logs.",
  },
  {
    code: "A.7.8",
    name: "Equipment siting and protection",
    type: controls_type.PHYSICAL,
    description: "Place and protect equipment to reduce theft/damage/unauthorized access.",
    guidance: "Secure racks, cable locks, restricted locations; evidence: equipment standards, photos, asset records.",
  },
  {
    code: "A.7.9",
    name: "Security of assets off-premises",
    type: controls_type.PHYSICAL,
    description: "Protect equipment and information used outside facilities.",
    guidance: "Travel guidance, encryption, tracking, reporting loss; evidence: policy, MDM, incident logs.",
  },
  {
    code: "A.7.10",
    name: "Storage media",
    type: controls_type.PHYSICAL,
    description: "Manage and protect removable and storage media.",
    guidance: "Media handling policy, encryption, control issuance, disposal; evidence: registers, configs, procedures.",
  },
  {
    code: "A.7.11",
    name: "Supporting utilities",
    type: controls_type.PHYSICAL,
    description: "Protect supporting utilities (power, water, telecom) to ensure availability.",
    guidance: "UPS/generators, redundant links where needed; evidence: maintenance/test logs, vendor contracts.",
  },
  {
    code: "A.7.12",
    name: "Cabling security",
    type: controls_type.PHYSICAL,
    description: "Protect power/telecom cabling from interception or damage.",
    guidance: "Use conduits, secure routes, restricted access to patch panels; evidence: cabling standards, inspections.",
  },
  {
    code: "A.7.13",
    name: "Equipment maintenance",
    type: controls_type.PHYSICAL,
    description: "Maintain equipment to ensure availability and prevent compromise.",
    guidance: "Scheduled maintenance, authorized technicians, secure maintenance access; evidence: maintenance tickets and logs.",
  },
  {
    code: "A.7.14",
    name: "Secure disposal or reuse of equipment",
    type: controls_type.PHYSICAL,
    description: "Ensure data is removed before disposal/reuse of equipment.",
    guidance: "Secure wipe, degauss, destruction, certificates; evidence: disposal records and sanitization logs.",
  },

  /* =========================
     A.8 TECHNOLOGICAL (34)
     ========================= */
  {
    code: "A.8.1",
    name: "User endpoint devices",
    type: controls_type.TECHNOLOGICAL,
    description: "Secure user endpoints (laptops, mobiles) that access information.",
    guidance: "MDM/EDR, disk encryption, patching, baseline hardening; evidence: compliance reports and configs.",
  },
  {
    code: "A.8.2",
    name: "Privileged access rights",
    type: controls_type.TECHNOLOGICAL,
    description: "Manage and control privileged access rights to minimize risk.",
    guidance: "PAM, separate admin accounts, approvals, session logging; evidence: PAM configs, access reviews, logs.",
  },
  {
    code: "A.8.3",
    name: "Information access restriction",
    type: controls_type.TECHNOLOGICAL,
    description: "Restrict access to information based on need-to-know and classification.",
    guidance: "RBAC/ABAC, segmentation, sensitive data controls; evidence: role matrix, ACLs, audit logs.",
  },
  {
    code: "A.8.4",
    name: "Access to source code",
    type: controls_type.TECHNOLOGICAL,
    description: "Protect source code repositories from unauthorized access or changes.",
    guidance: "Repo permissions, branch protection, code review, signed commits; evidence: repo settings and audit logs.",
  },
  {
    code: "A.8.5",
    name: "Secure authentication",
    type: controls_type.TECHNOLOGICAL,
    description: "Use secure authentication mechanisms for systems and services.",
    guidance: "MFA, strong password policy, SSO, secure session handling; evidence: IdP configs, MFA enforcement screenshots.",
  },
  {
    code: "A.8.6",
    name: "Capacity management",
    type: controls_type.TECHNOLOGICAL,
    description: "Ensure capacity and performance support availability requirements.",
    guidance: "Monitor resource usage, scaling plans, alerts; evidence: dashboards, capacity reviews, incident records.",
  },
  {
    code: "A.8.7",
    name: "Protection against malware",
    type: controls_type.TECHNOLOGICAL,
    description: "Prevent, detect, and respond to malware threats.",
    guidance: "AV/EDR, email filtering, allowlisting, user training; evidence: EDR policies, detection reports.",
  },
  {
    code: "A.8.8",
    name: "Management of technical vulnerabilities",
    type: controls_type.TECHNOLOGICAL,
    description: "Identify, assess, and remediate vulnerabilities in a timely manner.",
    guidance: "Vuln scanning, patch SLAs, risk acceptance process; evidence: scan reports, patch records, exceptions.",
  },
  {
    code: "A.8.9",
    name: "Configuration management",
    type: controls_type.TECHNOLOGICAL,
    description: "Manage secure configurations of systems and services.",
    guidance: "Baselines, IaC, change control, drift detection; evidence: baselines, config repos, CM tickets.",
  },
  {
    code: "A.8.10",
    name: "Information deletion",
    type: controls_type.TECHNOLOGICAL,
    description: "Delete information securely when no longer required.",
    guidance: "Retention + deletion procedures, secure erase, automated lifecycle; evidence: retention rules, deletion logs.",
  },
  {
    code: "A.8.11",
    name: "Data masking",
    type: controls_type.TECHNOLOGICAL,
    description: "Mask data to reduce exposure in non-production or limited contexts.",
    guidance: "Tokenization/masking for test data, partial reveal; evidence: masking rules, samples, approvals.",
  },
  {
    code: "A.8.12",
    name: "Data leakage prevention",
    type: controls_type.TECHNOLOGICAL,
    description: "Prevent unauthorized exfiltration of sensitive data.",
    guidance: "DLP policies (email, endpoint, cloud), monitoring; evidence: DLP configs, alerts, incident records.",
  },
  {
    code: "A.8.13",
    name: "Information backup",
    type: controls_type.TECHNOLOGICAL,
    description: "Back up information/systems to meet recovery requirements.",
    guidance: "Backup schedules, encryption, restore tests, RPO/RTO; evidence: backup reports and restore test results.",
  },
  {
    code: "A.8.14",
    name: "Redundancy of information processing facilities",
    type: controls_type.TECHNOLOGICAL,
    description: "Implement redundancy to meet availability needs.",
    guidance: "HA design, failover, redundant components; evidence: architecture diagrams, DR tests.",
  },
  {
    code: "A.8.15",
    name: "Logging",
    type: controls_type.TECHNOLOGICAL,
    description: "Produce and retain logs to support monitoring and investigations.",
    guidance: "Define log sources, fields, retention, integrity; evidence: logging policy, SIEM configs, sample logs.",
  },
  {
    code: "A.8.16",
    name: "Monitoring activities",
    type: controls_type.TECHNOLOGICAL,
    description: "Monitor systems and networks to detect anomalies and incidents.",
    guidance: "SIEM/alerts, use cases, triage workflow; evidence: alert rules, dashboards, incident tickets.",
  },
  {
    code: "A.8.17",
    name: "Clock synchronisation",
    type: controls_type.TECHNOLOGICAL,
    description: "Synchronize system clocks for accurate logs and correlation.",
    guidance: "NTP configuration, monitor drift; evidence: configs and monitoring outputs.",
  },
  {
    code: "A.8.18",
    name: "Use of privileged utility programs",
    type: controls_type.TECHNOLOGICAL,
    description: "Control use of powerful utilities that can bypass security.",
    guidance: "Restrict tools, approvals, monitoring, remove unused; evidence: allowlist and access logs.",
  },
  {
    code: "A.8.19",
    name: "Installation of software on operational systems",
    type: controls_type.TECHNOLOGICAL,
    description: "Control software installation to prevent unauthorized or unsafe software.",
    guidance: "Software allowlisting, admin rights control, package management; evidence: policies and endpoint configs.",
  },
  {
    code: "A.8.20",
    name: "Networks security",
    type: controls_type.TECHNOLOGICAL,
    description: "Secure networks to protect confidentiality, integrity, and availability.",
    guidance: "Network segmentation, firewalls, secure routing, monitoring; evidence: network diagrams and firewall rules.",
  },
  {
    code: "A.8.21",
    name: "Security of network services",
    type: controls_type.TECHNOLOGICAL,
    description: "Ensure network services are secure and meet agreed requirements.",
    guidance: "Secure DNS/DHCP/VPN/WiFi configs, SLAs, monitoring; evidence: configs and reviews.",
  },
  {
    code: "A.8.22",
    name: "Segregation of networks",
    type: controls_type.TECHNOLOGICAL,
    description: "Separate networks to reduce exposure and limit lateral movement.",
    guidance: "VLANs, security groups, micro-segmentation; evidence: segmentation design and rules.",
  },
  {
    code: "A.8.23",
    name: "Web filtering",
    type: controls_type.TECHNOLOGICAL,
    description: "Restrict access to malicious or inappropriate web resources.",
    guidance: "Proxy/DNS filtering, categories, blocklists, logging; evidence: web filter policy and reports.",
  },
  {
    code: "A.8.24",
    name: "Use of cryptography",
    type: controls_type.TECHNOLOGICAL,
    description: "Use cryptography to protect information appropriately.",
    guidance: "Crypto policy, TLS, encryption at rest, key management; evidence: standards, KMS configs, cert inventory.",
  },
  {
    code: "A.8.25",
    name: "Secure development life cycle",
    type: controls_type.TECHNOLOGICAL,
    description: "Integrate security into SDLC from planning to release.",
    guidance: "Security requirements, threat modeling, reviews, CI checks; evidence: SDLC policy and pipeline configs.",
  },
  {
    code: "A.8.26",
    name: "Application security requirements",
    type: controls_type.TECHNOLOGICAL,
    description: "Define security requirements for applications and services.",
    guidance: "Define authn/authz, logging, input validation, data protection; evidence: requirement templates and specs.",
  },
  {
    code: "A.8.27",
    name: "Secure system architecture and engineering principles",
    type: controls_type.TECHNOLOGICAL,
    description: "Apply secure architecture principles in system design.",
    guidance: "Least privilege, defense-in-depth, secure defaults; evidence: architecture reviews and checklists.",
  },
  {
    code: "A.8.28",
    name: "Secure coding",
    type: controls_type.TECHNOLOGICAL,
    description: "Develop software following secure coding practices to prevent vulnerabilities.",
    guidance: "Code standards, SAST, secrets scanning, peer review; evidence: guidelines, pipeline results, PR reviews.",
  },
  {
    code: "A.8.29",
    name: "Security testing in development and acceptance",
    type: controls_type.TECHNOLOGICAL,
    description: "Test security in dev and acceptance before release.",
    guidance: "SAST/DAST, dependency scanning, pentest where needed; evidence: test reports and remediation tickets.",
  },
  {
    code: "A.8.30",
    name: "Outsourced development",
    type: controls_type.TECHNOLOGICAL,
    description: "Manage security risks when development is outsourced.",
    guidance: "Supplier security requirements, code ownership, reviews, access control; evidence: contracts, onboarding, audits.",
  },
  {
    code: "A.8.31",
    name: "Separation of development, test and production environments",
    type: controls_type.TECHNOLOGICAL,
    description: "Separate environments to reduce risk of unauthorized changes/exposure.",
    guidance: "Network/account separation, data controls, least privilege; evidence: environment diagrams and IAM policies.",
  },
  {
    code: "A.8.32",
    name: "Change management",
    type: controls_type.TECHNOLOGICAL,
    description: "Control changes to systems and services to reduce risk.",
    guidance: "Change requests, approvals, testing, rollback plans; evidence: change tickets, CAB minutes.",
  },
  {
    code: "A.8.33",
    name: "Test information",
    type: controls_type.TECHNOLOGICAL,
    description: "Protect test data and ensure it is appropriate and authorized.",
    guidance: "Use synthetic/masked data, restrict access, retention rules; evidence: test data policy and controls.",
  },
  {
    code: "A.8.34",
    name: "Protection of information systems during audit testing",
    type: controls_type.TECHNOLOGICAL,
    description: "Protect systems during audit/assessment testing to avoid disruption or exposure.",
    guidance: "Define rules of engagement, scope, approvals, safety controls; evidence: audit test plan and approvals.",
  },
] as const;

export const ISO27001_CONTROL_BY_CODE = new Map(
  ISO27001_CONTROLS_CATALOG.map((c) => [c.code, c])
);
